project:
  type: book
  output-dir: docs
lang: fr

book:
  title: "guide-R"
  subtitle: "Guide pour l'analyse de données d'enquêtes avec R"
  author:
    - name: Joseph Larmarange
      orcid: 0000-0001-7097-700X
      url: https://joseph.larmarange.net
      affiliations: IRD, Ceped
  date: today
  chapters:
    - index.qmd
    - part: "**Rappels**"
      chapters: 
        - rappels/vecteurs.qmd
        - rappels/listes.qmd
        - rappels/facteurs.qmd
    - part: "**Manipulation de données**"
      chapters:
        - manipulation/dates.qmd
  search:
    type: overlay
  repo-url: https://github.com/larmarange/guide-R/
  repo-actions: [source, issue]
  downloads: [pdf]
  sharing: [twitter, facebook, linkedin]
  output-file: guide-R
  sidebar:
    style: "docked"
  page-footer: 
    border: true
    background: primary
    left: "guide-R : Guide pour l'analyse de données d'enquêtes avec R" 
    right: 
      - icon: github
        href: https://github.com/larmarange/guide-R/
      - icon: youtube 
        href: https://www.youtube.com/c/webinR
      - text: "analyse-R"
        href: https://larmarange.github.io/analyse-R/
      - text: "webin-R"
        href: https://larmarange.github.io/webin-R/

bibliography: references.bib

format:
  html:
    theme: flatly
    css: styles.css
    code-link: true
    code-overflow: wrap
    code-copy: true
    code-line-numbers: true
  pdf:
    documentclass: scrreprt

execute: 
  cache: true
  tidy: styler
  freeze: auto

highlight-style: pygments
reference-location: margin
citation-location: margin
filters: 
  - lightbox
lightbox: auto

comments:
  giscus:
    repo: larmarange/guide-R
    repo-id: R_kgDOH6-xnw
    category: "Forum"
    category-id: DIC_kwDOH6-xn84CRLQy
    loading: lazy
    mapping: pathname
    language: fr
    reactions-enabled: true
