project:
  type: book
  output-dir: docs
lang: fr

book:
  title: "guide-R"
  subtitle: "Guide pour l'analyse de données d'enquêtes avec R"
  cover-image: ressources/cover.png
  favicon: ressources/favicon.png
  author:
    - name: Joseph Larmarange
      orcid: 0000-0001-7097-700X
      url: https://joseph.larmarange.net
      affiliations: IRD, Ceped
  date: today
  date-format: long
  google-analytics: "G-8BT7D9P85Y"
  cookie-consent: true
  chapters:
    - index.qmd
    - part: "**Bases du langage**"
      chapters: 
        - bases/packages.qmd
        - bases/vecteurs.qmd
        - bases/listes.qmd
        - bases/tableaux_donnees.qmd
        - bases/tibbles.qmd
        - bases/attributs.qmd
    - part: "**Manipulation de données**"
      chapters:
        - manipulation/pipe.qmd
        - manipulation/dplyr.qmd
        - manipulation/facteurs.qmd
        - manipulation/combiner-variables.qmd
        - manipulation/etiquettes-variables.qmd
        - manipulation/etiquettes-valeurs.qmd
        - manipulation/valeurs-manquantes.qmd
        - manipulation/import-export.qmd
        - manipulation/formater-nombre.qmd
        - manipulation/couleurs.qmd
    - part: "**Analyses**"
      chapters:
        - analyses/ggplot2.qmd
        - analyses/statistique-univariee.qmd
        - analyses/statistique-bivariee.qmd
        - analyses/regression-lineaire.qmd
        - analyses/regression-logistique-binaire.qmd
        - analyses/estimations-marginales.qmd
        - analyses/contrastes.qmd
        - analyses/interactions.qmd
        - analyses/multicolinearite.qmd
    - part: "**Données pondérées avec `survey`**"
      chapters:
        - donnees_ponderees/plan-echantillonnage.qmd
        - donnees_ponderees/manipulation.qmd
        - donnees_ponderees/analyses-bivariees.qmd
    - part: "**Manipulation avancée**"
      chapters:
        - manipulation_avancee/dates.qmd
        - manipulation_avancee/tidyr.qmd
  search:
    type: overlay
  repo-url: https://github.com/larmarange/guide-R/
  repo-actions: [source, issue]
  downloads: [pdf]
  sharing: [twitter, facebook, linkedin]
  output-file: guide-R
  sidebar: 
    border: true
    logo: ressources/typewriter.png
  page-footer: 
    border: true
    background: light
    left: 
      - text: "guide-R : Guide pour l'analyse de données d'enquêtes avec R"
      - icon: cc-circle
        href: http://creativecommons.org/licenses/by-nc-sa/4.0/
    right: 
      - icon: github
        href: https://github.com/larmarange/guide-R/
      - icon: youtube 
        href: https://www.youtube.com/c/webinR
      - text: "analyse-R"
        href: https://larmarange.github.io/analyse-R/
      - text: "webin-R"
        href: https://larmarange.github.io/webin-R/

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    code-link: true
    code-overflow: wrap
    code-copy: true
    code-line-numbers: true
    smooth-scroll: true
    cap-location: margin
  pdf:
    documentclass: scrreprt

execute: 
  freeze: auto

reference-location: margin
citation-location: margin
filters: 
  - lightbox
lightbox: auto

comments:
  giscus:
    repo: larmarange/guide-R
    repo-id: R_kgDOH6-xnw
    category: "Forum"
    category-id: DIC_kwDOH6-xn84CRLQy
    loading: lazy
    mapping: pathname
    language: fr
    reactions-enabled: true
    
