project:
  type: book
  output-dir: docs
lang: fr

book:
  title: "tuto-R"
  subtitle: "Tutoriel sur l’analyse d’enquêtes avec **R** & le *tidyverse*"
  author:
    - name:
        given: Joseph
        family: Larmarange
      orcid: 0000-0001-7097-700X
      url: https://joseph.larmarange.net
      affiliations: IRD, Ceped
  date: today
  chapters:
    - index.qmd
    - part: "**Section**"
      chapters: 
        - test.qmd
    - references.qmd
  search:
    type: overlay
  repo-url: https://github.com/larmarange/tuto-R/
  repo-actions: [source, issue]
  sharing: [twitter, facebook, linkedin]
  output-file: tuto-R
  sidebar:
    style: "docked"
  page-footer: 
    border: true
    background: primary
    left: "tuto-R : analyse d’enquêtes avec **R** & le *tidyverse*" 
    right: 
      - icon: github
        href: https://github.com/larmarange/tuto-R/
      - icon: youtube 
        href: https://www.youtube.com/c/webinR

bibliography: references.bib

format:
  html:
    theme: flatly
    css: styles.css
    code-link: true
    code-overflow: wrap
    code-copy: true
    code-line-numbers: true

execute: 
  cache: true
  tidy: styler
  freeze: auto

highlight-style: pygments
reference-location: margin
citation-location: margin
filters: 
  - lightbox
lightbox: auto

comments:
  giscus:
    repo: larmarange/analyse-R
    category: "Questions & Réponses"
    loading: lazy
    mapping: title
    language: fr
    reactions-enabled: true
